# Configuration for builds on readthedocs.org

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-23.11"

conda:
  environment: environment-rtd.yaml

# Only build HTML and JSON formats
formats: []
