name: sphinx-linkcheck

on:
  push:
    branches: ['*']
  schedule:
    - cron: 43 4 8 * *  # 04:43 UTC on the 8th day of each month

jobs:
  sphinx-linkcheck:
    name: linkcheck
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
           miniforge-variant: Mambaforge-pypy3
           miniforge-version: latest
           use-mamba: true
           auto-update-conda: false
           auto-activate-base: false
           channels: conda-forge,nodefaults
           channel-priority: true
           environment-file: environment-rtd.yaml
           activate-environment: salishseacast-docs

      - name: linkcheck
        shell: bash -l {0}
        run: |
          make linkcheck

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Sphinx linkcheck
          fields: repo,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_SALISHSEACAST_WEBHOOK_URL }}
        if: always()
